language: python
python:
  - "2.7"
branches:
  only:
    - master
install:
  - pip install -r codalab/requirements/dev_azure_nix.txt --use-mirrors
script:
  - cd codalab
  - python manage.py test apps/authenz

